name: Compile & Common Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.3.3

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Common Test
      run: rebar3 ct --readable true
