name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-tests:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.3.4

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Unit tests
      run: rebar3 eunit
    - name: Start epmd
      run: epmd -daemon
    - name: System tests
      run: rebar3 ct --name seppen-0-255@127.0.0.1 --setcookie YGzma2DLnRUUqJxR --suite seppen_SUITE
    - name: Distributed tests
      run: rebar3 ct --name ct_master@127.0.0.1 --setcookie YGzma2DLnRUUqJxR --suite seppen_dist_SUITE
